/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Customer = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Policy = IDL.Record({
  'documents' : IDL.Vec(ExternalBlob),
  'validFrom' : Time,
  'insuranceCompany' : IDL.Text,
  'policyType' : IDL.Text,
  'validTo' : Time,
  'customerId' : IDL.Principal,
  'roadTaxExpiry' : Time,
  'policyNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPolicy' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Principal,
        Time,
        Time,
        Time,
        IDL.Vec(ExternalBlob),
      ],
      [],
      [],
    ),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getCustomer' : IDL.Func([IDL.Principal], [Customer], ['query']),
  'getCustomerPolicies' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Policy)],
      ['query'],
    ),
  'getPolicy' : IDL.Func([IDL.Text], [Policy], ['query']),
  'getUpcomingExpirations' : IDL.Func([IDL.Nat], [IDL.Vec(Policy)], ['query']),
  'listCustomers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Customer))],
      ['query'],
    ),
  'listPolicies' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Policy))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Customer = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Policy = IDL.Record({
    'documents' : IDL.Vec(ExternalBlob),
    'validFrom' : Time,
    'insuranceCompany' : IDL.Text,
    'policyType' : IDL.Text,
    'validTo' : Time,
    'customerId' : IDL.Principal,
    'roadTaxExpiry' : Time,
    'policyNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPolicy' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Principal,
          Time,
          Time,
          Time,
          IDL.Vec(ExternalBlob),
        ],
        [],
        [],
      ),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getCustomer' : IDL.Func([IDL.Principal], [Customer], ['query']),
    'getCustomerPolicies' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Policy)],
        ['query'],
      ),
    'getPolicy' : IDL.Func([IDL.Text], [Policy], ['query']),
    'getUpcomingExpirations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Policy)],
        ['query'],
      ),
    'listCustomers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Customer))],
        ['query'],
      ),
    'listPolicies' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Policy))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };