/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'alertType' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Customer {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Policy {
  'documents' : Array<ExternalBlob>,
  'validFrom' : Time,
  'insuranceCompany' : string,
  'policyType' : string,
  'validTo' : Time,
  'customerId' : Principal,
  'roadTaxExpiry' : Time,
  'policyNumber' : string,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCustomer' : ActorMethod<[string, string, string], undefined>,
  'addPolicy' : ActorMethod<
    [string, string, string, Principal, Time, Time, Time, Array<ExternalBlob>],
    undefined
  >,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getCustomer' : ActorMethod<[Principal], Customer>,
  'getCustomerPolicies' : ActorMethod<[Principal], Array<Policy>>,
  'getPolicy' : ActorMethod<[string], Policy>,
  'getUpcomingExpirations' : ActorMethod<[bigint], Array<Policy>>,
  'listCustomers' : ActorMethod<[], Array<[Principal, Customer]>>,
  'listPolicies' : ActorMethod<[], Array<[string, Policy]>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];